Repository Hercute/MCRA-FE, pull requests merged in 2024-07, with the labels that each got.

#9 Feat/login/#8 로그인 폼 제작 및 간단한 CSS
  src/app/login/page.tsx
  src/app/login/style.css
Labels: 개발

#12 Feat/main/#11 하단 메뉴바
  src/app/layout.tsx
  src/components/layout/Menu.tsx
  src/components/layout/style.css
Labels: 개발

#15 Feat/signup/#10 회원가입 폼 ui 제작
  src/app/signup/page.tsx
  src/app/signup/style.css
Labels: 개발

#17 Style/font/#16 woff 폰트 적용
  public/font/SCDream1.otf
  public/font/SCDream2.otf
  public/font/SCDream3.otf
  public/font/SCDream4.otf
  public/font/SCDream5.otf
  public/font/SCDream6.otf
  public/font/SCDream7.otf
  public/font/SCDream8.otf
  public/font/SCDream9.otf
  src/app/globals.css
  src/app/layout.tsx
Labels: 개발

#18 [delete] #16 otf 파일 삭제
  public/font/SCDream1.otf
  public/font/SCDream2.otf
  public/font/SCDream3.otf
  public/font/SCDream4.otf
  public/font/SCDream5.otf
  public/font/SCDream6.otf
  public/font/SCDream7.otf
  public/font/SCDream8.otf
  public/font/SCDream9.otf
Labels: 개발, 세팅

#21 Feat/profile/#19 프로필 선택 ui 제작
  src/app/signup/page.tsx
  src/app/signup/style.css
  src/assets/profile/profile1.png
  src/assets/profile/profile2.png
  src/assets/profile/profile3.png
  src/assets/profile/profile4.png
  src/assets/profile/profile5.png
Labels: 개발

#24 Feat/fridge/#23 냉장고 추가 페이지 대분류 ui 제작 및 라우팅 수정
  src/app/fridge/add/page.tsx
  src/app/fridge/food/page.tsx
  src/app/fridge/food/style.css
  src/app/fridge/page.tsx
Labels: 개발, 문서

#26 Feat/css/#25 CSS root 컬러 설정
  src/app/globals.css
Labels: 개발, 세팅

#28 Feat/layout/#27 메뉴바 숨김 레이아웃 추가 및 냉장고 라우팅 폴더명 변경
  src/app/(menuBar)/cart/page.tsx
  src/app/(menuBar)/data/recipeDummyData.ts
  src/app/(menuBar)/fridge/item/page.tsx
  src/app/(menuBar)/fridge/item/style.css
  src/app/(menuBar)/fridge/page.tsx
  src/app/(menuBar)/layout.tsx
  src/app/(menuBar)/mypage/page.tsx
  src/app/(menuBar)/recipe/AuthRecipeList.css
  src/app/(menuBar)/recipe/AuthRecipeList.tsx
  src/app/(menuBar)/recipe/RecipeItem.css
  src/app/(menuBar)/recipe/RecipeItem.tsx
  src/app/(menuBar)/recipe/RecipeList.tsx
  src/app/(menuBar)/recipe/RecommendMenuList.tsx
  src/app/(menuBar)/recipe/[id]/edit/page.tsx
  src/app/(menuBar)/recipe/[id]/page.tsx
  src/app/(menuBar)/recipe/page.tsx
  src/app/(menuBar)/recipe/upload/HashTag.tsx
  src/app/(menuBar)/recipe/upload/RecipeIngredient.tsx
  src/app/(menuBar)/recipe/upload/RecipeOrder.tsx
  src/app/(menuBar)/recipe/upload/RecipeRegister.tsx
  src/app/(menuBar)/recipe/upload/RecipeUpload.tsx
  src/app/(menuBar)/recipe/upload/page.tsx
  src/app/(menuBar)/recipe/upload/upload.css
  src/app/layout.tsx
  src/app/page.tsx
Labels: 개발, 수정

#30 Feat/main/#29 메인 페이지 작업, 상단 헤더 작업
  src/app/page.tsx
  src/assets/button/button.png
  src/components/layout/MainHeader.tsx
  src/components/layout/style.css
Labels: 개발

#31 Feat/recipe/#20
  src/app/(menuBar)/recipe/upload/RecipeOrder.tsx
  src/app/(menuBar)/recipe/upload/RecipeRegister.tsx
  src/app/(menuBar)/recipe/upload/upload.css
  src/types/recipe.ts
Labels: 개발

#34 [feat]#32:레시피올리기uiux-조리순서까지
  src/app/(menuBar)/recipe/upload/HashTag.tsx
  src/app/(menuBar)/recipe/upload/RecipeIngredient.tsx
  src/app/(menuBar)/recipe/upload/RecipeOrder.tsx
  src/app/(menuBar)/recipe/upload/RecipeUpload.tsx
  src/app/(menuBar)/recipe/upload/upload.css
  src/app/globals.css
Labels: 세팅

#35 [feat]#32:레시피올리기 메인이미지업로드
  src/app/(menuBar)/recipe/upload/RecipeRegister.tsx
  src/app/(menuBar)/recipe/upload/RecipeUpload.tsx
  src/app/(menuBar)/recipe/upload/upload.css
  src/recoil/atoms/recoilState.ts
  src/types/recipe.ts
Labels: 개발, 세팅

#36 Style/fridge/#33 냉장고 대분류 ui 스타일 수정
  public/images/button_deep_orange.png
  public/images/button_orange.png
  src/app/(menuBar)/fridge/item/page.tsx
  src/app/(menuBar)/fridge/item/style.css
  src/app/page.tsx
Labels: 개발, 수정

#39 [fix]#37: 변수명 변경
  src/app/(menuBar)/recipe/upload/RecipeIngredient.tsx
  src/app/(menuBar)/recipe/upload/RecipeOrder.tsx
  src/app/(menuBar)/recipe/upload/RecipeRegister.tsx
  src/app/(menuBar)/recipe/upload/RecipeUpload.tsx
  src/recoil/atoms/recoilState.ts
  src/types/recipe.ts
Labels: 수정
